# make_shortcut.ps1 -- Create / update the ChaseOS Studio desktop shortcut.
# Points to the source launcher (.bat) so no rebuild is ever needed.
# Safe to re-run at any time.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File "...\make_shortcut.ps1" [-VaultRoot "C:\path"] [-IconPath "C:\path\to\icon.ico"]
#
# Icon resolution order:
#   1. -IconPath argument              (explicit override -- use this to set a custom icon)
#   2. runtime\studio\shell\chaseos_studio.ico  (generated by export_icon.py)
#   3. dist\studio\ChaseOS-Studio.exe  (embedded icon from the built EXE)
#   4. No icon  (Windows default blank shortcut icon)
#
# To regenerate the icon file:
#   .venv\Scripts\python.exe runtime\studio\shell\export_icon.py

param(
    [string]$VaultRoot = "",
    [string]$IconPath  = ""
)

if ($VaultRoot -eq "") {
    # Script lives at runtime\studio\shell\ -- go 3 levels up to reach vault root
    $ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
    $VaultRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $ScriptDir))
}
$VaultRoot = (Resolve-Path $VaultRoot).Path

$BatPath  = "$VaultRoot\runtime\studio\shell\launch_studio.bat"
$ExePath  = "$VaultRoot\dist\studio\ChaseOS-Studio.exe"
$Desktop  = [System.Environment]::GetFolderPath("Desktop")
$LnkPath  = "$Desktop\ChaseOS Studio.lnk"

if (-not (Test-Path $BatPath)) {
    Write-Error "Launcher not found at $BatPath"
    exit 1
}

# Resolve icon: explicit arg > EXE embedded > nothing
$ResolvedIcon = ""
if ($IconPath -ne "" -and (Test-Path $IconPath)) {
    $ResolvedIcon = (Resolve-Path $IconPath).Path
    Write-Host "Using custom icon: $ResolvedIcon" -ForegroundColor Cyan
} elseif ($IconPath -ne "") {
    Write-Warning "Icon not found at '$IconPath' -- falling back to EXE icon."
}

$GeneratedIco = "$VaultRoot\runtime\studio\shell\chaseos_studio.ico"
if ($ResolvedIcon -eq "" -and (Test-Path $GeneratedIco)) {
    $ResolvedIcon = $GeneratedIco
    Write-Host "Using generated icon: $ResolvedIcon" -ForegroundColor Cyan
}

if ($ResolvedIcon -eq "" -and (Test-Path $ExePath)) {
    $ResolvedIcon = "$ExePath,0"
}

$ws = New-Object -ComObject WScript.Shell
$sc = $ws.CreateShortcut($LnkPath)
$sc.TargetPath       = "C:\Windows\System32\cmd.exe"
$sc.Arguments        = "/c `"$BatPath`""
$sc.WorkingDirectory = $VaultRoot
$sc.Description      = "ChaseOS Studio"
$sc.WindowStyle      = 7

if ($ResolvedIcon -ne "") {
    # .ico files use "path,0"; EXE string already has ",0" appended above
    if ($ResolvedIcon -match ",\d+$") { $IconEntry = $ResolvedIcon } else { $IconEntry = "$ResolvedIcon,0" }
    $sc.IconLocation = $IconEntry
}

$sc.Save()

# Notify Explorer to refresh shortcut icon immediately
$sig = @"
using System;
using System.Runtime.InteropServices;
public class NativeShellRefresh {
    [DllImport("shell32.dll")]
    public static extern void SHChangeNotify(int wEventId, int uFlags, IntPtr dwItem1, IntPtr dwItem2);
}
"@
try {
    Add-Type -TypeDefinition $sig -ErrorAction SilentlyContinue
    [NativeShellRefresh]::SHChangeNotify(0x08000000, 0x0000, [IntPtr]::Zero, [IntPtr]::Zero)
} catch {}

Write-Host "Shortcut written: $LnkPath" -ForegroundColor Green
Write-Host "Target: cmd.exe /c launch_studio.bat (always runs live source)"
if ($ResolvedIcon -ne "") {
    Write-Host "Icon:   $ResolvedIcon" -ForegroundColor Gray
} else {
    Write-Host "Icon:   (none -- no .exe or explicit icon found)" -ForegroundColor Gray
    Write-Host "Tip:    Re-run with -IconPath 'C:\path\to\chaseos.ico' to set a custom icon." -ForegroundColor Yellow
}
