"""Non-mutating Agent Bus review-request contracts for Pulse candidates.

This module turns read-only Pulse candidate inspector rows into Agent Bus
review request previews. It deliberately does not import the Agent Bus writer,
create tasks, persist approval requests, apply candidates, or mutate canonical
ChaseOS state.
"""

from __future__ import annotations

import hashlib
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from runtime.pulse.card_schema import now_utc
from runtime.pulse.candidate_inspector import (
    INSPECTOR_BLOCKED_EFFECTS,
    PulseCandidateInspectorItem,
    build_candidate_inspector_snapshot,
)


PULSE_BUS_REVIEW_INTENT = "REVIEW"
PULSE_BUS_REVIEW_STATUS = "contract_ready"
PULSE_BUS_DEFAULT_SENDER = "Operator"
PULSE_BUS_DEFAULT_RECIPIENT = "Hermes"
PULSE_BUS_REVIEW_BLOCKED_EFFECTS = tuple(
    sorted(
        set(INSPECTOR_BLOCKED_EFFECTS)
        | {
            "agent_bus_task_creation",
            "agent_bus_mutation",
            "candidate_apply",
            "approval_persistence",
            "live_runtime_dispatch",
        }
    )
)


def _safe_text(value: str | None, fallback: str) -> str:
    cleaned = " ".join(str(value or "").split())
    return cleaned or fallback


def _candidate_ref(item: PulseCandidateInspectorItem) -> str:
    candidate_ref = item.candidate_id or item.related_candidate_id or item.record_id
    return _safe_text(candidate_ref, "unknown-candidate")


def _contract_id(item: PulseCandidateInspectorItem, recipient: str, requested_by: str) -> str:
    seed = "|".join(
        [
            item.item_id,
            item.item_kind,
            _candidate_ref(item),
            item.candidate_kind or "",
            recipient,
            requested_by,
        ]
    )
    digest = hashlib.sha256(seed.encode("utf-8")).hexdigest()[:12]
    return f"pulse-bus-review-contract-{digest}"


def _work_fingerprint(item: PulseCandidateInspectorItem) -> str:
    candidate_kind = item.candidate_kind or "unknown"
    runtime_part = f":{item.runtime_id}" if item.runtime_id else ""
    return f"pulse-candidate-review:{candidate_kind}{runtime_part}:{_candidate_ref(item)}"


def _request_text(item: PulseCandidateInspectorItem) -> str:
    candidate_ref = _candidate_ref(item)
    target = f" target={item.target_ref}" if item.target_ref else ""
    runtime = f" runtime={item.runtime_id}" if item.runtime_id else ""
    return (
        f"Review Pulse {item.candidate_kind or 'candidate'} candidate {candidate_ref} "
        f"from {item.item_kind}.{runtime}{target} "
        "Return a bounded review recommendation with evidence, blockers, required "
        "operator approvals, and any runtime coordination risks. Do not apply the "
        "candidate or mutate ChaseOS state."
    )


def _expected_output_text(item: PulseCandidateInspectorItem) -> str:
    return (
        "Agent Bus REVIEW result packet only: recommendation, rationale, evidence refs, "
        "blocked effects, and required approvals. No feedback application, memory "
        "approval, Personal Map mutation, runtime-memory mutation, task/SOP creation, "
        "schedule activation, provider/connector call, or canonical writeback."
    )


def _notes_text(item: PulseCandidateInspectorItem, requested_by: str) -> str:
    refs = []
    if item.source_log_path:
        refs.append(f"source_log={item.source_log_path}")
    if item.source_deck_path:
        refs.append(f"source_deck={item.source_deck_path}")
    if item.source_card_id:
        refs.append(f"source_card={item.source_card_id}")
    ref_text = "; ".join(refs) if refs else "no source artifact refs declared"
    return (
        f"Generated by ChaseOS Pulse contract preview for {requested_by}. "
        f"{ref_text}. Contract is non-mutating and must not be enqueued or applied "
        "without a later explicit approval pass."
    )


@dataclass
class PulseAgentBusReviewRequestContract:
    """Preview contract for routing one Pulse candidate to Agent Bus review."""

    contract_id: str
    candidate_id: str
    source_item_id: str
    source_item_kind: str
    candidate_kind: str
    request: str
    expected_output: str
    sender: str = PULSE_BUS_DEFAULT_SENDER
    recipient: str = PULSE_BUS_DEFAULT_RECIPIENT
    intent: str = PULSE_BUS_REVIEW_INTENT
    priority: str = "normal"
    contract_status: str = PULSE_BUS_REVIEW_STATUS
    created_at: str = field(default_factory=now_utc)
    requested_by: str = "operator"
    source_surface: str = "ChaseOS Pulse"
    source_log_path: str | None = None
    source_deck_path: str | None = None
    source_card_id: str | None = None
    source_surface_path: str | None = None
    target_ref: str | None = None
    runtime_id: str | None = None
    work_fingerprint: str | None = None
    artifacts: tuple[str, ...] = field(default_factory=tuple)
    notes: str = ""
    approval_required: bool = True
    allow_external_sender_required: bool = True
    bus_task_creation_allowed: bool = False
    bus_task_written: bool = False
    writes_performed: bool = False
    candidate_apply_allowed: bool = False
    approval_request_written: bool = False
    canonical_writeback_allowed: bool = False
    mutates_canonical_state: bool = False
    second_datastore_write_allowed: bool = False
    provider_or_connector_call_allowed: bool = False
    schedule_activation_allowed: bool = False
    live_runtime_dispatch_allowed: bool = False
    blocked_effects: tuple[str, ...] = PULSE_BUS_REVIEW_BLOCKED_EFFECTS

    def validate(self) -> None:
        if not self.contract_id:
            raise ValueError("contract_id is required")
        if not self.candidate_id:
            raise ValueError("candidate_id is required")
        if not self.source_item_id:
            raise ValueError("source_item_id is required")
        if not self.source_item_kind:
            raise ValueError("source_item_kind is required")
        if not self.candidate_kind:
            raise ValueError("candidate_kind is required")
        if self.sender != PULSE_BUS_DEFAULT_SENDER:
            raise ValueError("Pulse bus review contracts must use Operator as bus sender")
        if not self.recipient:
            raise ValueError("recipient is required")
        if self.intent != PULSE_BUS_REVIEW_INTENT:
            raise ValueError("Pulse bus review contracts must use REVIEW intent")
        if self.priority not in {"low", "normal", "high"}:
            raise ValueError("Pulse bus review contract priority must be low, normal, or high")
        if self.contract_status != PULSE_BUS_REVIEW_STATUS:
            raise ValueError("Pulse bus review contracts must remain contract_ready")
        if not self.request:
            raise ValueError("request is required")
        if not self.expected_output:
            raise ValueError("expected_output is required")
        if not self.approval_required:
            raise ValueError("Pulse bus review contracts require approval")
        if not self.allow_external_sender_required:
            raise ValueError("Operator sender requires explicit external-sender allowance")
        if self.bus_task_creation_allowed:
            raise ValueError("Pulse bus review contracts cannot allow task creation in this pass")
        if self.bus_task_written:
            raise ValueError("Pulse bus review contracts cannot mark bus tasks as written")
        if self.writes_performed:
            raise ValueError("Pulse bus review contracts cannot perform writes")
        if self.candidate_apply_allowed:
            raise ValueError("Pulse bus review contracts cannot allow candidate apply")
        if self.approval_request_written:
            raise ValueError("Pulse bus review contracts cannot persist approval requests")
        if self.canonical_writeback_allowed:
            raise ValueError("Pulse bus review contracts cannot allow canonical writeback")
        if self.mutates_canonical_state:
            raise ValueError("Pulse bus review contracts cannot mutate canonical state")
        if self.second_datastore_write_allowed:
            raise ValueError("Pulse bus review contracts cannot write a second datastore")
        if self.provider_or_connector_call_allowed:
            raise ValueError("Pulse bus review contracts cannot call providers or connectors")
        if self.schedule_activation_allowed:
            raise ValueError("Pulse bus review contracts cannot activate schedules")
        if self.live_runtime_dispatch_allowed:
            raise ValueError("Pulse bus review contracts cannot dispatch runtimes live")
        if set(self.blocked_effects) != set(PULSE_BUS_REVIEW_BLOCKED_EFFECTS):
            raise ValueError("Pulse bus review contracts must declare blocked effects")

    def to_task_preview(self) -> dict[str, Any]:
        """Return the Agent Bus task fields a later approval pass may enqueue."""
        self.validate()
        return {
            "sender": self.sender,
            "recipient": self.recipient,
            "intent": self.intent,
            "priority": self.priority,
            "request": self.request,
            "expected_output": self.expected_output,
            "notes": self.notes,
            "work_fingerprint": self.work_fingerprint,
            "allow_external_sender_required": self.allow_external_sender_required,
            "bus_task_creation_allowed": self.bus_task_creation_allowed,
        }

    def to_dict(self) -> dict[str, Any]:
        self.validate()
        payload = asdict(self)
        payload["artifacts"] = list(self.artifacts)
        payload["blocked_effects"] = list(self.blocked_effects)
        payload["agent_bus_task_preview"] = self.to_task_preview()
        return payload


def build_agent_bus_review_request_contract(
    item: PulseCandidateInspectorItem,
    *,
    recipient: str = PULSE_BUS_DEFAULT_RECIPIENT,
    requested_by: str = "operator",
    priority: str = "normal",
    created_at: str | None = None,
) -> PulseAgentBusReviewRequestContract:
    """Build a non-mutating Agent Bus review request preview for one item."""
    item.validate()
    clean_recipient = _safe_text(recipient, PULSE_BUS_DEFAULT_RECIPIENT)
    clean_requested_by = _safe_text(requested_by, "operator")
    candidate_ref = _candidate_ref(item)
    artifacts = tuple(
        ref
        for ref in (
            item.source_log_path,
            item.source_deck_path,
            item.source_surface_path,
        )
        if ref
    )
    contract = PulseAgentBusReviewRequestContract(
        contract_id=_contract_id(item, clean_recipient, clean_requested_by),
        candidate_id=candidate_ref,
        source_item_id=item.item_id,
        source_item_kind=item.item_kind,
        candidate_kind=item.candidate_kind or "unknown",
        request=_request_text(item),
        expected_output=_expected_output_text(item),
        recipient=clean_recipient,
        priority=priority,
        created_at=created_at or now_utc(),
        requested_by=clean_requested_by,
        source_log_path=item.source_log_path,
        source_deck_path=item.source_deck_path,
        source_card_id=item.source_card_id,
        source_surface_path=item.source_surface_path,
        target_ref=item.target_ref,
        runtime_id=item.runtime_id,
        work_fingerprint=_work_fingerprint(item),
        artifacts=artifacts,
        notes=_notes_text(item, clean_requested_by),
    )
    contract.validate()
    return contract


def build_agent_bus_review_request_contract_for_candidate(
    vault_root: str | Path,
    candidate_id: str,
    *,
    recipient: str = PULSE_BUS_DEFAULT_RECIPIENT,
    requested_by: str = "operator",
    priority: str = "normal",
    created_at: str | None = None,
) -> PulseAgentBusReviewRequestContract:
    """Load a candidate read-only and build its Agent Bus review preview."""
    clean_candidate_id = _safe_text(candidate_id, "")
    if not clean_candidate_id:
        raise ValueError("candidate_id is required")

    snapshot = build_candidate_inspector_snapshot(vault_root, candidate_id=clean_candidate_id)
    if not snapshot.items:
        raise ValueError(f"Pulse candidate not found: {clean_candidate_id}")

    candidate_items = [item for item in snapshot.items if item.item_kind != "review_decision"]
    source_item = candidate_items[0] if candidate_items else snapshot.items[0]
    return build_agent_bus_review_request_contract(
        source_item,
        recipient=recipient,
        requested_by=requested_by,
        priority=priority,
        created_at=created_at,
    )
