"""ChaseOS-named bounded draft tools for Runtime MCP."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from runtime.mcp.config import MCPConfig
from runtime.mcp.errors import input_error
from runtime.mcp.types import HandlerResult, PermissionEnvelope


ALLOWED_WRITE_ROOTS = [
    "07_LOGS/Operator-Briefs/_drafts/",
    "07_LOGS/Agent-Activity/",
]

FORBIDDEN_PREFIXES = [
    "00_HOME/",
    "01_PROJECTS/",
    "02_KNOWLEDGE/",
    "03_INPUTS/",
    "04_SOPS/",
    "05_TEMPLATES/",
    "06_AGENTS/",
    "runtime/",
    ".env",
    "secrets/",
    "credentials/",
]


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


def _safe_slug(raw: Any, fallback: str) -> str:
    value = str(raw or fallback).lower().strip()
    value = re.sub(r"[^a-z0-9_.-]+", "-", value).strip("-")
    return value[:70] or fallback


def _normalize_target(target: str) -> str:
    normalized = target.replace("\\", "/").lstrip("/")
    while "//" in normalized:
        normalized = normalized.replace("//", "/")
    return normalized


def _is_allowed_target(target: str) -> tuple[bool, str]:
    if not target or Path(target).is_absolute():
        return False, "target must be a non-empty relative path"
    normalized = _normalize_target(target)
    if ".." in Path(normalized).parts:
        return False, "path traversal is forbidden"
    for prefix in FORBIDDEN_PREFIXES:
        if normalized == prefix.rstrip("/") or normalized.startswith(prefix):
            return False, f"target is in forbidden zone {prefix}"
    for root in ALLOWED_WRITE_ROOTS:
        root_norm = root.rstrip("/")
        if normalized == root_norm or normalized.startswith(root_norm + "/"):
            return True, "allowed draft/audit target"
    return False, "target is outside ChaseOS Runtime MCP draft/audit allowlist"


def chaseos_validate_writeback_target(
    params: dict[str, Any],
    config: MCPConfig,
    envelope: PermissionEnvelope,
) -> HandlerResult:
    target = params.get("target")
    if not isinstance(target, str):
        return HandlerResult(False, error=input_error("invalid_target", "target must be a string"))
    allowed, reason = _is_allowed_target(target)
    return HandlerResult(
        True,
        {
            "tool": "chaseos.validate_writeback_target",
            "target": _normalize_target(target),
            "allowed": allowed,
            "reason": reason,
            "canonical_writeback": False,
        },
        audit_metadata={"tool": "chaseos.validate_writeback_target", "allowed": allowed},
    )


def _write_draft(
    *,
    config: MCPConfig,
    filename_prefix: str,
    title: str,
    body: str,
    metadata: dict[str, Any],
) -> HandlerResult:
    now = _utc_now()
    slug = _safe_slug(metadata.get("slug"), filename_prefix)
    rel = f"07_LOGS/Operator-Briefs/_drafts/{now.strftime('%Y-%m-%d')}-{filename_prefix}-{slug}.md"
    allowed, reason = _is_allowed_target(rel)
    if not allowed:
        return HandlerResult(False, error=input_error("write_target_denied", reason, target=rel))
    path = config.vault_root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    content = "\n".join(
        [
            "---",
            "status: DRAFT",
            "canonical_writeback: false",
            f"created_at_utc: {now.isoformat()}",
            "---",
            "",
            f"# {title}",
            "",
            body.strip(),
            "",
            "## Runtime Boundary",
            "Generated by ChaseOS Runtime MCP draft tool. This is not canonical writeback.",
        ]
    )
    path.write_text(content + "\n", encoding="utf-8")
    return HandlerResult(
        True,
        {"path": rel, "status": "draft_written", "canonical_writeback": False},
        files_written=[rel],
        audit_metadata={"draft_tool": filename_prefix, **metadata},
    )


def chaseos_generate_operator_brief_draft(
    params: dict[str, Any],
    config: MCPConfig,
    envelope: PermissionEnvelope,
) -> HandlerResult:
    body = str(params.get("body") or "Draft operator brief requested through Runtime MCP.")
    return _write_draft(
        config=config,
        filename_prefix="operator-brief-draft",
        title="Operator Brief Draft",
        body=body,
        metadata={"slug": params.get("slug"), "tool": "chaseos.generate_operator_brief_draft"},
    )


def chaseos_create_research_digest_draft(
    params: dict[str, Any],
    config: MCPConfig,
    envelope: PermissionEnvelope,
) -> HandlerResult:
    body = str(params.get("body") or "Draft research digest requested through Runtime MCP.")
    return _write_draft(
        config=config,
        filename_prefix="research-digest-draft",
        title="Research Digest Draft",
        body=body,
        metadata={"slug": params.get("slug"), "tool": "chaseos.create_research_digest_draft"},
    )


def chaseos_prepare_discord_alert_draft(
    params: dict[str, Any],
    config: MCPConfig,
    envelope: PermissionEnvelope,
) -> HandlerResult:
    body = str(params.get("body") or "Draft Discord alert requested through Runtime MCP.")
    return _write_draft(
        config=config,
        filename_prefix="discord-alert-draft",
        title="Discord Alert Draft",
        body=body,
        metadata={"slug": params.get("slug"), "tool": "chaseos.prepare_discord_alert_draft"},
    )


def chaseos_query_sic_evidence(
    params: dict[str, Any],
    config: MCPConfig,
    envelope: PermissionEnvelope,
) -> HandlerResult:
    query = params.get("query")
    if not isinstance(query, str) or not query.strip():
        return HandlerResult(False, error=input_error("invalid_query", "query must be a non-empty string"))
    readme_rel = "runtime/source_intelligence/README.md"
    readme = config.vault_root / readme_rel
    excerpt = readme.read_text(encoding="utf-8", errors="replace")[:1200] if readme.exists() else ""
    return HandlerResult(
        True,
        {
            "tool": "chaseos.query_sic_evidence",
            "query": query.strip(),
            "mode": "summary_stub",
            "evidence": [{"source": readme_rel, "excerpt": excerpt}] if excerpt else [],
            "canonical_writeback": False,
        },
        files_read=[readme_rel] if excerpt else [],
        audit_metadata={"tool": "chaseos.query_sic_evidence", "query_length": len(query.strip())},
    )

