"""
sbp_strikezone_digest.py — StrikeZone Market Digest Publisher (Phase 9 Pass 1E)

First named SBP instance pipeline. Extends SBPBaseHandler and implements
generate_content() to produce a daily morning digest for the StrikeZone community.

Pass 1E upgrade: LLM synthesis via runtime execution adapter.
  generate_content() routes synthesis through execute_synthesis(), which reads
  runtime/{execution_adapter}/model_config.yaml to select the runtime/model chain.
  Feature code does not import SDKs, call providers, or read provider secrets.
  Synthesis falls back gracefully to the formatted Python dump if synthesis fails.

This is an INSTANCE pipeline — it runs on top of the generic SBP substrate.
It does not modify the substrate. StrikeZone logic stays here, not in runtime/sbp/.

Inputs:
  vault-notes adapter (trust tier 1):
    - 00_HOME/Now.md          — current system state and phase context
    - 01_PROJECTS/StrikeZone/StrikeZone-Crypto-OS.md  — StrikeZone project state
  acquisition-pack adapter (trust tier 2, optional):
    - briefing_ready_input_set produced by runtime/acquisition/ SourcePackBuilder
    - Provides normalized source text, trust/freshness metadata, actionability contract
    - Includes live staged captures (Perplexity, Grok) from Pass 1D pre-capture

Output:
  - LLM-synthesized markdown digest, written to 07_LOGS/SBP-Runs/YYYY-MM-DD-sbp_strikezone_digest-run.md
  - Delivered to Discord via DISCORD_WEBHOOK_URL env var (if configured)
  - Delivered to vault-local (always)

Authority boundaries:
  - No canonical writes — output goes to 07_LOGS/SBP-Runs/ only
  - No knowledge promotion
  - No protected file writes
  - No provider credentials in feature code — synthesis secrets are runtime adapter-owned
  - Discord delivery credential remains DISCORD_WEBHOOK_URL from env only
  - Acquisition pack content is briefing_only per its actionability contract
  - Synthesis runtime/model chain declared in runtime/{execution_adapter}/model_config.yaml

AOR engine registration:
  _handlers["sbp_strikezone_digest"] = run_sbp_strikezone_digest

Public API:
    StrikeZoneDigestHandler
    run_sbp_strikezone_digest(inputs, vault_root, manifest=None) -> dict
    WorkflowExecutionError
"""

from __future__ import annotations

import re
from datetime import date
from pathlib import Path

from runtime.sbp.base_handler import SBPBaseHandler, SBPWorkflowExecutionError
from runtime.execution_adapters.execute import (
    execute_synthesis,
    ExecutionAdapterError,
    ExecutionAdapterCredentialError,
)

# Re-export as WorkflowExecutionError for AOR engine import consistency
WorkflowExecutionError = SBPWorkflowExecutionError

# ── Digest template ────────────────────────────────────────────────────────────

_DIGEST_HEADER = """---
pipeline_id: sbp_strikezone_digest
date: {run_date}
type: morning-digest
source: sbp-strikezone-digest-pipeline
---"""

_DIGEST_FOOTER = "\n\n---\n*Generated by ChaseOS SBP — sbp_strikezone_digest | {run_date}*"

_MAX_SECTION_CHARS = 1200  # keep each vault section concise in the digest


# ── Handler ────────────────────────────────────────────────────────────────────

class StrikeZoneDigestHandler(SBPBaseHandler):
    """Instance handler for the StrikeZone Market Digest Publisher.

    Reads Now.md + StrikeZone-Crypto-OS.md via the vault-notes input adapter,
    combines with the acquisition pack (live Perplexity + Grok captures),
    and synthesizes a morning digest through the runtime's configured model.
    """
    workflow_id = "sbp_strikezone_digest"

    def generate_content(
        self, collected_inputs: dict, vault_root: Path, *, sbp_config=None
    ) -> str:
        """Synthesize the morning digest via the runtime's configured model.

        Consumes:
          - vault-notes: Now.md + StrikeZone-Crypto-OS.md (canonical system context)
          - acquisition-pack: briefing_ready_input_set normalized sources (optional,
            includes live Perplexity + Grok staged captures from Pass 1D)

        Routes synthesis through execute_synthesis() → runtime model_config.yaml.
        Falls back to Python-formatted dump if synthesis is unavailable. The digest
        should still publish vault-local output instead of escalating solely because
        optional runtime synthesis is offline.
        """
        run_date = date.today().isoformat()

        vault_data = collected_inputs.get("vault-notes", {})
        raw_content: str = vault_data.get("content") or ""

        system_section = _extract_section(raw_content, "Now.md", _MAX_SECTION_CHARS)
        strikezone_section = _extract_section(raw_content, "StrikeZone-Crypto-OS.md", _MAX_SECTION_CHARS)

        acq_data = collected_inputs.get("acquisition-pack", {})
        acq_content: str = acq_data.get("content") or ""
        acq_stub: bool = acq_data.get("stub", True)
        acq_trust: dict = acq_data.get("trust_summary", {})
        acq_freshness: dict = acq_data.get("freshness_summary", {})
        acq_blocked: list = acq_data.get("blocked_actions", [])

        has_acquisition = bool(acq_content and not acq_stub)

        # Resolve execution adapter from sbp_config
        execution_adapter = "openclaw"  # safe default
        if sbp_config is not None and hasattr(sbp_config, "execution_adapter"):
            execution_adapter = sbp_config.execution_adapter or "openclaw"

        # Build synthesis prompt
        prompt_system, prompt_user = _build_synthesis_prompt(
            run_date=run_date,
            system_section=system_section,
            strikezone_section=strikezone_section,
            acq_content=acq_content if has_acquisition else "",
            acq_trust=acq_trust,
            acq_freshness=acq_freshness,
            acq_blocked=acq_blocked,
        )

        try:
            synthesis = execute_synthesis(
                prompt_system=prompt_system,
                prompt_user=prompt_user,
                execution_adapter=execution_adapter,
                vault_root=vault_root,
            )
            synthesized_body = synthesis.text
            synthesis_note = (
                f"*Synthesized by {synthesis.runtime} / {synthesis.model_id}"
                f"{' (fallback)' if synthesis.fallback_used else ''}*"
            )
        except ExecutionAdapterCredentialError as exc:
            synthesized_body = _format_fallback_digest(
                run_date=run_date,
                system_section=system_section,
                strikezone_section=strikezone_section,
                acq_content=acq_content,
                acq_stub=acq_stub,
                acq_trust=acq_trust,
                acq_freshness=acq_freshness,
                acq_blocked=acq_blocked,
            )
            synthesis_note = f"*Synthesis unavailable — formatted fallback digest. Missing credential: {exc}*"
        except ExecutionAdapterError as exc:
            # Non-fatal degradation: fall back to Python-formatted dump
            synthesized_body = _format_fallback_digest(
                run_date=run_date,
                system_section=system_section,
                strikezone_section=strikezone_section,
                acq_content=acq_content,
                acq_stub=acq_stub,
                acq_trust=acq_trust,
                acq_freshness=acq_freshness,
                acq_blocked=acq_blocked,
            )
            synthesis_note = f"*Synthesis unavailable — formatted fallback digest. Error: {exc}*"

        header = _DIGEST_HEADER.format(run_date=run_date)
        footer = _DIGEST_FOOTER.format(run_date=run_date)
        return f"{header}\n\n{synthesized_body}\n\n{synthesis_note}{footer}"


def _build_synthesis_prompt(
    *,
    run_date: str,
    system_section: str,
    strikezone_section: str,
    acq_content: str,
    acq_trust: dict,
    acq_freshness: dict,
    acq_blocked: list,
) -> tuple[str, str]:
    """Build (system_prompt, user_prompt) for the StrikeZone morning digest synthesis."""
    prompt_system = (
        "You are the StrikeZone briefing synthesizer. Your job is to produce a concise, "
        "actionable morning digest for active crypto and risk-asset traders. "
        "Tone: direct, professional, no fluff. Format: structured markdown with clear sections. "
        "Base your analysis strictly on the provided inputs — do not invent data. "
        "If a section's source material is thin, say so briefly rather than padding. "
        "Output the full digest as clean markdown. No preamble, no meta-commentary."
    )

    sections: list[str] = [f"# StrikeZone Morning Brief — {run_date}", ""]

    sections += [
        "## Operator Context (Now.md)",
        system_section or "*Not available.*",
        "",
    ]

    sections += [
        "## StrikeZone Project State (StrikeZone-Crypto-OS.md)",
        strikezone_section or "*Not available.*",
        "",
    ]

    if acq_content:
        trust_line = _format_trust_line(acq_trust)
        stale_note = ""
        if acq_freshness.get("stale_items"):
            stale_count = len(acq_freshness["stale_items"])
            stale_note = f"\n*{stale_count} stale source(s) — flag in digest.*"
        blocked_note = ""
        if acq_blocked:
            blocked_note = f"\n*Blocked actions per acquisition contract: {', '.join(acq_blocked[:5])}*"
        max_acq = _MAX_SECTION_CHARS * 4
        trimmed_acq = acq_content[:max_acq]
        if len(acq_content) > max_acq:
            trimmed_acq += "\n\n*(source material truncated — work with what is shown)*"
        sections += [
            f"## Live Market Sources{stale_note}{blocked_note}",
            f"{trust_line}",
            "",
            trimmed_acq,
            "",
        ]
    else:
        sections += [
            "## Live Market Sources",
            "*No live acquisition data — brief based on vault context only.*",
            "",
        ]

    prompt_user_parts = [
        "Using the input material below, produce the StrikeZone morning digest. "
        "Structure it with these sections:\n"
        "1. **Market Overview** — key macro and crypto conditions (from live sources if present)\n"
        "2. **Key Levels to Watch** — price levels, catalysts, or setups that matter today\n"
        "3. **Operator Context** — what the system state says about current phase and priorities\n"
        "4. **Session Notes** — pre-market window notes and risk considerations\n\n"
        "Keep each section tight. No filler. Flag stale data if noted above.\n\n"
        "---\n",
        *sections,
    ]
    prompt_user = "\n".join(prompt_user_parts)

    return prompt_system, prompt_user


def _format_fallback_digest(
    *,
    run_date: str,
    system_section: str,
    strikezone_section: str,
    acq_content: str,
    acq_stub: bool,
    acq_trust: dict,
    acq_freshness: dict,
    acq_blocked: list,
) -> str:
    """Python-formatted fallback digest when LLM synthesis is unavailable."""
    lines = [
        f"# StrikeZone Morning Digest — {run_date}",
        "",
        "## System Context",
        "",
        system_section or "*Now.md not available.*",
        "",
        "## StrikeZone Project State",
        "",
        strikezone_section or "*StrikeZone-Crypto-OS.md not available.*",
        "",
    ]

    if acq_content and not acq_stub:
        lines += [
            "## Acquisition Sources",
            "",
            _format_trust_line(acq_trust),
            "",
        ]
        if acq_freshness.get("stale_items"):
            stale_count = len(acq_freshness["stale_items"])
            lines.append(f"*Stale sources: {stale_count} — verify before citing in session.*")
            lines.append("")
        if acq_blocked:
            blocked_preview = ", ".join(acq_blocked[:3])
            suffix = "..." if len(acq_blocked) > 3 else ""
            lines.append(f"*Acquisition contract — blocked actions: {blocked_preview}{suffix}*")
            lines.append("")
        max_acq = _MAX_SECTION_CHARS * 3
        trimmed = acq_content[:max_acq]
        if len(acq_content) > max_acq:
            trimmed += "\n\n*(acquisition sources truncated)*"
        lines += [trimmed, ""]
    else:
        lines += [
            "## Acquisition Sources",
            "",
            "*No acquisition pack available — digest based on vault context only.*",
            "",
        ]

    lines += [
        "## Session Notes",
        "",
        "Daily market session — pre-market window (NY 0600 ET).",
        "Review the above context before entering positions.",
        "",
    ]

    return "\n".join(lines)


def _format_trust_line(trust_summary: dict) -> str:
    """Format a single-line trust summary from an acquisition pack trust_summary dict."""
    t1 = trust_summary.get("tier1_count", 0)
    t2 = trust_summary.get("tier2_count", 0)
    t3 = trust_summary.get("tier3_count", 0)
    t4 = trust_summary.get("tier4_count", 0)
    conflicts = len(trust_summary.get("conflicts", []))
    conflict_note = f" | **{conflicts} conflict(s)**" if conflicts else ""
    return (
        f"*Trust summary — tier1: {t1}, tier2: {t2}, tier3: {t3}, tier4: {t4}{conflict_note}*"
    )


def _extract_section(raw: str, filename_hint: str, max_chars: int) -> str:
    """Extract and trim the section corresponding to filename_hint from raw content."""
    if not raw:
        return ""

    # VaultNotesInputAdapter joins sections with: "# <rel_path>\n\n<content>"
    # Split on section headers that start with "# " followed by a path
    parts = re.split(r"(?m)^# .+\n\n", raw)
    headers = re.findall(r"(?m)^# .+", raw)

    for i, header in enumerate(headers):
        if filename_hint in header and i < len(parts) - 1:
            section_text = parts[i + 1].split("\n\n---\n\n")[0].strip()
            if len(section_text) > max_chars:
                section_text = section_text[:max_chars] + "\n\n*(truncated)*"
            return section_text

    # Fallback: return first max_chars of raw if no section match
    if raw:
        truncated = raw[:max_chars]
        return truncated + ("\n\n*(truncated)*" if len(raw) > max_chars else "")
    return ""


# ── Review dispatch ────────────────────────────────────────────────────────────

def _attempt_review_dispatch(artifact_path: str, vault_root: Path) -> dict | None:
    """Post a review task to the agent bus after digest production. Fail-open — never raises."""
    try:
        from runtime.agent_bus.bus import create_task  # late import avoids hard dep
        return create_task(
            vault_root,
            sender="OpenClaw",
            recipient="Hermes",
            intent="REVIEW",
            priority="normal",
            request=(
                "Review the StrikeZone morning digest for structural completeness. "
                "Check: headings present, date marker exists, word count reasonable, "
                "no obvious synthesis failures."
            ),
            expected_output=(
                "Structured review with endorsed items and flags. "
                "Post result to bus — no canonical writes."
            ),
            notes=f"artifact_path: {artifact_path}\nAuto-posted by sbp_strikezone_digest.",
        )
    except Exception:
        return None


# ── AOR dispatch function ──────────────────────────────────────────────────────

def run_sbp_strikezone_digest(inputs: dict, vault_root: Path, manifest: dict | None = None) -> dict:
    """AOR dispatch entry point for sbp_strikezone_digest.

    Called by engine._stage_run() when workflow_id == 'sbp_strikezone_digest'.
    Requires manifest to access sbp_config.
    """
    if manifest is None:
        raise WorkflowExecutionError(
            "sbp_strikezone_digest: manifest required for SBP dispatch — "
            "cannot validate sbp_config without manifest"
        )
    handler = StrikeZoneDigestHandler()
    result = handler.run(manifest, inputs, vault_root)

    # Post review task after successful digest production (fail-open)
    writebacks = result.get("writebacks", [])
    digest_path = next(
        (wb["path"] for wb in writebacks if wb.get("path", "").endswith(".md")),
        None,
    )
    if digest_path:
        result["review_task"] = _attempt_review_dispatch(digest_path, vault_root)

    return result
